### ISSUE TITLE
Custom styling of studio help

### ISSUE THREAD

**Issue by JohnatanNorman** [sanity-io/sanity#1920]
### I've been messing around with custom styling for the studio, and I couldn't pinpoint the variable to style this:
![Screen Shot 2020-06-13 at 9 32 09 PM](https://user-images.githubusercontent.com/41754671/84576453-8cbf6880-adbd-11ea-8409-72a6130b1ed8.png)
### My styles are as follow
```css
@import url('https://fonts.googleapis.com/css?family=Montserrat&display=swap');

:root {
	--block-editor-base-font-family: inherit;
	--block-editor-header-font-family: inherit;
	--block-extras-background-color: var(--grey-lightest);
	--block-extras-border-color: var(--gray-lighter);
	--block-extras-width: 10rem;
	--body-bg: var(--brand-primary);
	--body-text: var(--white-base);
	--brand-primary: #172530;
	--brand-secondary: #1f3241;
	--code-bg: var(--gray-light);
	--code-color: var(--brand-primary);
	--component-bg: var(--brand-secondary);
	--component-text-color: var(--white-base);
	--default-button-color--active: var(--brand-secondary);
	--default-button-color--hover: var(--brand-secondary);
	--default-button-color--inverted: var(--brand-secondary);
	--default-button-danger-color--inverted: var(--white-base);
	--default-button-danger-color: var(--state-danger-color);
	--default-button-primary-color--inverted: var(--white-base);
	--default-button-primary-color: var(--brand-primary);
	--default-button-success-color--inverted: var(--white-base);
	--default-button-success-color: var(--state-success-color);
	--default-button-warning-color--inverted: var(--state-warning-color--inverted);
	--default-button-warning-color: var(--state-warning-color);
	--dialog-header-color--inverted: var(--body-text);
	--dialog-header-color: var(--brand-primary);
	--font-family-sans-serif: 'Montserrat', sans-serif;
	--font-size-base: 16px;
	--gray--transparent: color(var(--gray-base) a(60%));
	--gray-base: #e9e9e9;
	--gray-dark--transparent: color(var(--gray-base) a(70%));
	--gray-dark: color(var(--gray-base));
	--gray-darker-transparent: color(var(--gray-base) lightness(+ 2%) a(88%));
	--gray-darker: color(var(--gray-base) lightness(+ 2%));
	--gray-darkest--transparent: color(var(--gray-base) lightness(- 5%) a(95%));
	--gray-darkest: color(var(--gray-base) lightness(- 5%));
	--gray-light--transparent: color(var(--component-bg) lightness(+ 10%) a(50%));
	--gray-light: color(var(--component-bg) lightness(+ 10%));
	--gray-lighter--transparent: color(var(--component-bg) lightness(+ 15%) a(25%));
	--gray-lighter: color(var(--component-bg) lightness(+ 15%));
	--gray-lightest--transparent: color(var(--component-bg) lightness(+ 30%) a(50%));
	--gray-lightest: color(var(--component-bg) lightness(+ 30%));
	--gray: color(var(--gray-base));
	--input-bg: var(--brand-primary);
	--input-border-color-active: var(--gray-lightest);
	--input-border-color-focus: var(--gray-lightest);
	--input-border-color-hover: var(--gray-light);
	--input-border-color: var(--gray-base);
	--input-color: var(--white-base);
	--main-navigation-color--inverted: var(--white-base);
	--main-navigation-color: var(--brand-primary);
	--pre-bg: var(--gray-light);
	--selectable-item-base: var(--brand-primary);
	--selectable-item-color--inverted: var(--gray-base);
	--selectable-item-color-highlighted: var(--brand-primary);
	--text-selection-color: color(var(--white-base) alpha(20%));
	--white-base: #fafafa;
}
```
### Did I miss something or is it a bug?
