### ISSUE TITLE
'Unauthorized - Session does not match project host' (Github actions deployment)

### ISSUE THREAD

**Issue by martyjg** [sanity-io/sanity#3975]
**Describe the bug**

When trying to deploy Sanity from github actions I'm getting the following error
```
Run npx @sanity/cli deploy
  npx @sanity/cli deploy
  shell: sh -e {0}
  env:
    SANITY_STUDIO_PREVIEW_TOKEN: ***
    SANITY_STUDIO_API_PROJECT_ID: iuuqva9
    SANITY_AUTH_TOKEN: ***
  
- Checking project info

ClientError$1: Unauthorized - Session does not match project host. You may need to login again with sanity login.
```

I assumed this meant that the deploy and viewer tokens had expired so I created new tokens and added them to the project but it's still happening. I checked and double-checked these.
I understand what 'login again with sanity login' would mean if I was running these from my command line but in the context of deployment / github actions, I don't know what to do here.
  

**To Reproduce**

As a step in a github workflow job:
```     
- name: Deploy live studio
        run: npx @sanity/cli deploy
        working-directory: website/cms
        env:
          SANITY_STUDIO_PREVIEW_TOKEN: ${{ secrets.SANITY_STUDIO_PREVIEW_TOKEN }}
          SANITY_STUDIO_API_PROJECT_ID: iuu3qva9
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN_PRODUCTION }}
```
**Expected behavior**

Sanity deploys. I made no changes to the github actions / workflow that could have caused this.

**Which versions of Sanity are you using?**

package.json:
"@sanity/client": "^3.4.1",

'sanity versions':
@sanity/cli  2.27.0 (latest: 3.0.6)

**What operating system are you using?**
This is happening on github actions.

**Which versions of Node.js / npm are you running?**

```
8.14.0
v16.13.1
```
